import type { Metadata } from "next";
import {Sora } from "next/font/google";
import "./globals.css";
import {NavBar} from "@/components/NavBar";
import {ReactNode} from "react";

const sora = Sora({subsets:['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
      <NavBar/>
      {children}
      </body>
    </html>
  );
}
